# Generated by Django 5.1.5 on 2025-04-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
