# Generated by Django 5.1.5 on 2025-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_learning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
